# Generated by Django 3.2.3 on 2021-05-20 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('responsavel', models.CharField(blank=True, max_length=180, null=True)),
                ('email', models.CharField(blank=True, max_length=180, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
