# Generated by Django 3.2.3 on 2021-05-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tarefas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='status_change_count',
            field=models.IntegerField(default=0),
        ),
    ]
